/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package hotel.reservation.system;

import java.awt.Image;
import java.io.FileInputStream;
import java.io.FileOutputStream;
import java.io.IOException;
import java.io.ObjectInputStream;
import java.io.ObjectOutputStream;
import java.util.HashMap;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JFrame;

/**
 *
 * @author Omar
 */
public class AfterManagerUI extends javax.swing.JFrame {

    /**
     * Creates new form AfterManagerUI
     */
    public AfterManagerUI(String title) {
        initComponents();
        setTitle(title);
    }
    HashMap<String,String> table1 = new HashMap<String,String>();
    HashMap<String,String> table2 = new HashMap<String,String>();

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Back = new javax.swing.JLabel();
        btn7 = new javax.swing.JButton();
        btn8 = new javax.swing.JButton();
        btn9 = new javax.swing.JButton();
        btn11 = new javax.swing.JButton();
        btn12 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(472, 709));
        setResizable(false);
        getContentPane().setLayout(null);

        Back.setText("");
        Back.setIcon(new ImageIcon(new ImageIcon("C:\\Users\\Omar\\Desktop\\Hotel reservation system\\Back.png")
            .getImage().getScaledInstance(60, 60, Image.SCALE_DEFAULT)));
    Back.addMouseListener(new java.awt.event.MouseAdapter() {
        public void mouseClicked(java.awt.event.MouseEvent evt) {
            BackMouseClicked(evt);
        }
    });
    getContentPane().add(Back);
    Back.setBounds(0, 0, 77, 50);

    btn7.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
    btn7.setForeground(new java.awt.Color(255, 255, 255));
    btn7.setText("Add Manager Username");
    btn7.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 2, true));
    btn7.setContentAreaFilled(false);
    btn7.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            btn7ActionPerformed(evt);
        }
    });
    getContentPane().add(btn7);
    btn7.setBounds(110, 180, 260, 70);

    btn8.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
    btn8.setForeground(new java.awt.Color(255, 255, 255));
    btn8.setText("Add Receptionist Username");
    btn8.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 2, true));
    btn8.setContentAreaFilled(false);
    btn8.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            btn8ActionPerformed(evt);
        }
    });
    getContentPane().add(btn8);
    btn8.setBounds(110, 310, 260, 70);

    btn9.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
    btn9.setForeground(new java.awt.Color(255, 255, 255));
    btn9.setText("Add Employee");
    btn9.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 2, true));
    btn9.setContentAreaFilled(false);
    btn9.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            btn9ActionPerformed(evt);
        }
    });
    getContentPane().add(btn9);
    btn9.setBounds(110, 50, 260, 70);

    btn11.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
    btn11.setForeground(new java.awt.Color(255, 255, 255));
    btn11.setText("Active Chat");
    btn11.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 2, true));
    btn11.setContentAreaFilled(false);
    btn11.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            btn11ActionPerformed(evt);
        }
    });
    getContentPane().add(btn11);
    btn11.setBounds(110, 540, 260, 60);

    btn12.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
    btn12.setForeground(new java.awt.Color(255, 255, 255));
    btn12.setText("Statistics");
    btn12.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 2, true));
    btn12.setContentAreaFilled(false);
    btn12.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            btn12ActionPerformed(evt);
        }
    });
    getContentPane().add(btn12);
    btn12.setBounds(110, 440, 260, 60);

    jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hotel/reservation/system/images/1 (3).jpg"))); // NOI18N
    jLabel1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
    getContentPane().add(jLabel1);
    jLabel1.setBounds(-10, -20, 490, 750);

    pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BackMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BackMouseClicked
        LogInUI m = new LogInUI("Grand Hotel");
        m.setVisible(true);
        setVisible(false);
        m.setLocationRelativeTo(null);
        m.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
    }//GEN-LAST:event_BackMouseClicked

    private void btn7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn7ActionPerformed
        // TODO add your handling code here:
        AddManagerUI m = new AddManagerUI("Grand Hotel");
        m.setLocationRelativeTo(null);
        m.setVisible(true);
        setVisible(false);
        m.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
    }//GEN-LAST:event_btn7ActionPerformed

    private void btn8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn8ActionPerformed
        // TODO add your handling code here:
            AddRecUI after = new AddRecUI("Grand Hotel");
            after.setVisible(true);
            setVisible(false);
            after.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
            after.setLocationRelativeTo(null);
    }//GEN-LAST:event_btn8ActionPerformed

    private void btn9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn9ActionPerformed
        try {
            // TODO add your handling code here:
            AddEmployee after = new AddEmployee("Grand Hotel");
            after.setVisible(true);
            setVisible(false);
            after.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
            after.setLocationRelativeTo(null);
        } catch (IOException ex) {
            Logger.getLogger(AfterManagerUI.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_btn9ActionPerformed

    private void btn11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn11ActionPerformed
        try {
            // TODO add your handling code here:
            Server s = new Server();
            s.setVisible(true);
            s.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
            Thread t = new Thread(s);
            t.start();
        } catch (IOException ex) {
            Logger.getLogger(AfterManagerUI.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btn11ActionPerformed

    private void btn12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn12ActionPerformed
        // TODO add your handling code here:
        GraphicsStat g =new GraphicsStat();
        JFrame f = new JFrame();
        
        f.setSize(1000, 1000);
        f.add(g);
        f.setVisible(true);
        f.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        f.setLocationRelativeTo(null);
        
    }//GEN-LAST:event_btn12ActionPerformed

    public void addManager(String u,String p) throws IOException, ClassNotFoundException
    {
    
//        ObjectInputStream i = new ObjectInputStream(new FileInputStream("D://ManagerUsers.bin"));
//        table1=(HashMap<String, String>) i.readObject();
        table1.put(u, p);
        ObjectOutputStream bin = new ObjectOutputStream(new FileOutputStream("D://ManagerUsers.bin"));
        bin.writeObject(table1);
       
    }
    
    public void addReceptionist(String u,String p) throws IOException, ClassNotFoundException
    {
//        ObjectInputStream i = new ObjectInputStream(new FileInputStream("D://ReceptionistUsers.bin"));
//        table2=(HashMap<String, String>) i.readObject();
        table2.put(u, p);
        ObjectOutputStream bin = new ObjectOutputStream(new FileOutputStream("D://ReceptionistUsers.bin"));
        bin.writeObject(table2);
       
    }
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AfterManagerUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AfterManagerUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AfterManagerUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AfterManagerUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
//                new AfterManagerUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Back;
    private javax.swing.JButton btn11;
    private javax.swing.JButton btn12;
    private javax.swing.JButton btn7;
    private javax.swing.JButton btn8;
    private javax.swing.JButton btn9;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
